[package]
name = "solang-wrapper"
version = "0.3.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
contract-build = "3.0.1"
cty = "0.2.2"
inkwell = "0.2.0"
protobuf = "3.2.0"
solang = "0.3.1"

[build-dependencies]
protobuf-codegen = "3.2.0"
protoc-bin-vendored = "3.0.0"
